name: acc_dart_lib
description: .Provides access to the data maintained by an installation of Assetto Corsa Competizione (ACC) on Windows
version: 1.0.0
repository: https://github.com/Playology/acc_dart_lib

environment:
  sdk: ^3.5.3

dependencies:
  path_provider: ^2.1.5
  path: ^1.8.0
  charset: ^2.0.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
